# Generated by Django 2.2.12 on 2023-02-10 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedIp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('authkey', models.TextField(db_column='authKey')),
            ],
            options={
                'db_table': 'allowed_ip',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Banklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('bankcode', models.TextField(blank=True, db_column='bankCode', null=True)),
                ('bankname', models.TextField(blank=True, db_column='bankName', null=True)),
                ('biccode', models.TextField(blank=True, db_column='bicCode', null=True)),
                ('branchdesc', models.TextField(blank=True, db_column='branchDesc', null=True)),
                ('cntrycode', models.TextField(blank=True, db_column='cntryCode', null=True)),
                ('sortcode', models.TextField(blank=True, db_column='sortCode', null=True)),
            ],
            options={
                'db_table': 'bankList',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BankTransactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tdate', models.CharField(max_length=255)),
                ('customer_no', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.FloatField()),
                ('transid', models.CharField(db_column='transId', max_length=100)),
                ('account', models.CharField(blank=True, max_length=255, null=True)),
                ('transdate', models.CharField(db_column='transDate', max_length=255)),
                ('transremarks', models.CharField(db_column='transRemarks', max_length=255)),
                ('currency', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'bank_transactions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DepositErrors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=255)),
                ('transactiontype', models.CharField(db_column='transactionType', max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('error_list', models.TextField()),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'deposit_errors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InvoicesPaid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoicecode', models.CharField(blank=True, db_column='invoiceCode', max_length=255, null=True)),
                ('clientid', models.CharField(blank=True, db_column='clientID', max_length=11, null=True)),
                ('datetime', models.DateTimeField(blank=True, db_column='dateTime', null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('invoicedesc', models.CharField(blank=True, db_column='invoiceDesc', max_length=255, null=True)),
                ('amount', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'invoices_paid',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destacc', models.CharField(max_length=255)),
                ('amount', models.CharField(max_length=255)),
                ('service', models.CharField(max_length=255)),
                ('remarks', models.CharField(max_length=255)),
                ('referenceno', models.CharField(db_column='referenceNo', max_length=255)),
                ('transactiontype', models.CharField(db_column='transactionType', max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'payment_transaction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessedTransactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processed', models.TextField()),
                ('status', models.IntegerField(blank=True, null=True)),
                ('customername', models.CharField(blank=True, db_column='customerName', max_length=255, null=True)),
                ('customer_no', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('amount', models.CharField(max_length=255)),
                ('transid', models.CharField(db_column='transId', max_length=255)),
                ('transdate', models.CharField(db_column='transDate', max_length=255)),
                ('entrydate', models.DateTimeField(db_column='entryDate')),
            ],
            options={
                'db_table': 'processed_transactions',
                'managed': False,
            },
        ),
    ]
